### GET all items
GET http://localhost:3000/items
Accept: application/json
### GET a single item by ID
GET http://localhost:3000/items/1
Accept: application/json
###
GET http://localhost:3000/customers/sales/2025/6
Accept: application/json